arrowParens: "always"
bracketSameLine: true
bracketSpacing: false
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "strict"
jsxSingleQuote: false
printWidth: 100
proseWrap: "always"
quoteProps: "as-needed"
semi: true
singleAttributePerLine: false
singleQuote: false
spaceRedirects: true
useTabs: false
tabWidth: 4
trailingComma: "none"
vueIndentScriptAndStyle: true
overrides:
    -   files: "*.ts"
        options:
            parser: "babel-ts"
