### Send POST request with json body
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
    "name": "Test",
    "surname": "Test",
    "email": "test@test.com",
    "password": "Test123_",
    "twoFactorAuthentication": true
}


### Basic authorization.
GET http://127.0.0.1:5000/jwt
Authorization: Basic test@test.com Test123_

> {%
    client.global.set("jwt", response.body.jwt);
%}

### Basic authorization.
GET http://127.0.0.1:5000/jwt
Authorization: Basic test@test.com Test1234_

### Basic authorization.
GET http://127.0.0.1:5000/jwt

### Basic authorization.
GET http://127.0.0.1:5000/2fa/jwt
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "otp": "035275"
}

### Basic authorization.
GET http://127.0.0.1:5000/non-existent

### Basic authorization.
POST http://127.0.0.1:5000/not-found
Authorization: Basic test@test.com Test1234_

{}

### Basic authorization.
POST http://127.0.0.1:5000/jwt
Authorization: Basic test@test.com Test1234_

{}
