### Send POST request with json body
POST http://127.0.0.1:5000/users
Content-Type: application/json

{
    "name": "Test",
    "surname": "Test",
    "email": "test@test.com",
    "password": "Test123_",
    "twoFactorAuthentication": false
}

### Basic authorization.
GET http://127.0.0.1:5000/jwt
Authorization: Basic test@test.com Test123_

### Basic authorization.
GET http://127.0.0.1:5000/jwt
Authorization: Basic test@test.com Test1234_
